import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import ReduxProvider from "../redux/ReduxProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    locale: "en_US",
    // ... add more open graph meta tags kk
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <GoogleOAuthProvider clientId="1006740086739-hur0rkv9k7hf4rp40a4i4trjgg2bo7jg.apps.googleusercontent.com">
        <body
          className={
            "bg-white text-black min-h-screen m-0 flex place-items-center min-w-[320px]"
          }
        >
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
